config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"

  get "reply/:lesson_id/comments/:id", to: "comments#reply", as: "reply"

  resources :users

  resources :lessons do
    resources :sections
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:email])

    message = "A link to reset your password will be sent if the email is valid."

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
    end

    redirect_to root_path, notice: message
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to password_reset_path, alert: "Your token has expired. Please try again"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Password reset successful. Please log in."
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/views/password_resets/edit.html.erb
<div class="center-content">
  <h1>Reset Password</h1>
  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

  <div class="mb-3">
    <%= form.label :password, class: "form-label"  %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    <i class="fa-solid fa-eye js-toggle-password"></i>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation, class: "form-label"  %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    <i class="fa-solid fa-eye js-toggle-password"></i>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-dark" %>
  </div>
<% end %>
</div>

app/views/password_resets/new.html.erb
<div class="center-content">
  <h1>Reset Password</h1>
  <%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
      <%= form.label :email, class: "form-label"  %>
      <%= form.text_field :email, class: "form-control", placeholder: "email@site.com" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Reset Password", class: "btn btn-dark" %>
    </div>
  <% end %>
</div>