config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"

  get "reply/:lesson_id/comments/:id", to: "comments#reply", as: "reply"

  resources :users

  resources :lessons do
    resources :sections
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  has_rich_text :body

  validates :body, presence: true

  def get_username
    return User.find(self.user_id).username
  end

  def owned_by_current_user?
    return (user_id == Current.user.id) unless Current.user.nil?
  end

  def replies
    replies = Comment.where(parent_id: id)
    return replies
  end

  def get_parent_comment_id
    # replies to a common parent comment should have same parent id
    return parent_id === nil ? id : parent_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in, except: [:show]

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @comment = @lesson.comments.new(comment_params)    
    @comment.user_id = Current.user.id

    if @comment.save
      redirect_to lesson_path(@lesson), notice: "Comment posted"
    else
      redirect_to lesson_path(@lesson), alert: "Create comment failed"
    end
  end

  def edit
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to lesson_path(@lesson), notice: "Comment updated"
    else
      redirect_to lesson_path(@lesson), alert: "Update comment failed"
    end
  end

  def reply
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.valid?%>
  <div class="comment mb-3 rounded">
    <%= render "comments/show", comment: comment %>
  </div>
  <% comment.replies.each do |reply| %>
    <div class="reply mb-3 rounded">
      <%= render "comments/show", comment: reply %>
    </div>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ lesson, comment ] do |form| %>
  <%= form.hidden_field :parent_id, value: parent_id %>
  <div class="mb-3 rich-text-area rounded comments-section">
    <%= form.rich_text_area :body %>
  </div>
  <div class="mb-3">
    <%= form.button class: "btn btn-primary rounded-circle", title: "Comment" do %>
      <i class="fa-solid fa-comment"></i>
    <% end %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<span class="nameplate"><%= comment.get_username %> says:</span> 
<div class="mb-2">
  <%= comment.body %>
</div>
<hr class="opacity-10 bg-dark">
<p>Posted on: <%= comment.created_at.strftime("%F") %></p>
<% if comment.owned_by_current_user? %>
  <%= button_to edit_lesson_comment_path(@lesson, comment),
          remote: true,
          method: :get,
          class: "btn btn-secondary js-comment-btn mb-1 rounded-circle",
          title: "Edit comment" do %>
    <i class="fa-solid fa-pencil"></i>
  <% end %>
<% elsif Current.user %>
  <%= link_to '<i class="fa-solid fa-reply"></i>'.html_safe, 
          reply_path(@lesson, comment), 
          remote: true, 
          class: "btn btn-primary js-comment-btn rounded-circle",
          title: "Reply to comment" %>
<% end %>

app/views/comments/edit.js.erb
$(".comment-parent-div").replaceWith("<%= j render "form", 
                                        lesson: @lesson, 
                                        comment: @comment, 
                                        parent_id: @comment.parent_id %>")

app/views/comments/reply.js.erb
$("form").remove();
$("#active-reply-btn").replaceWith("<%= j render "form",
                                         lesson: @lesson,
                                         comment: @lesson.comments.new,
                                         parent_id: @comment.get_parent_comment_id %>");