config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"

  get "reply/:lesson_id/comments/:id", to: "comments#reply", as: "reply"

  resources :users

  resources :lessons do
    resources :sections
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if object && object.errors.any? %>
  <div class="alert alert-danger">
    <% object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash-message">
  <% if flash[:notice] %>
    <div class="container-fluid alert-message">
      <div class="alert alert-primary">
        <%= flash[:notice] %>
      </div>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="container-fluid alert-message" >
      <div class="alert alert-warning">
        <%= flash[:alert] %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<section id="footer">
  <hr>
  <p> &copy; 2022 EigoFriends</p>  
</section>

app/views/shared/_lesson_main.html.erb
<section id="main">
  <div class="container-fluid chalkboard">
    <div id="lesson-main">
      <div id="lesson-sidebar">
        <p class="mb-2">Contents</p>
        <ul>
          <% @lesson.get_sections.sort_by(&:created_at).each do |section| %>
            <li class="mb-1">
              <a class="section-link js-section-toggle" data-section-header="<%= section.header %>"><%= section.header %></a>
            </li>
          <% end %>
        </ul>
      </div>
      <div id="lesson-body">
        <div class="mx-auto" id="lesson-title" >
          <%= @lesson.title %>
        </div>
        <%= render @lesson.sections %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<section id="header">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
      <%= image_tag "logo.png", id: "logo" %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "レッスン", lessons_path, class: "nav-link" %>
          </li>
          <% if Current.user %>
            <li class="nav-item dropdown me-2">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><%= Current.user.username %></a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "ダッシュボード", dashboard_path(Current.user), class: "dropdown-item" %>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <%= link_to "ログアウト", logout_path, class: "dropdown-item", method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "ログイン", sign_in_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</section>