config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"

  get "reply/:lesson_id/comments/:id", to: "comments#reply", as: "reply"

  resources :users

  resources :lessons do
    resources :sections
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :sections, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  validates :title, presence: true, uniqueness: true

  def visible?
    return status === "visible"
  end
  
  def get_sections
    return self.sections.select { |section| section.persisted? }
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :forbid_student_user, except: [:index, :show]

  def index
    @lessons = Lesson.order(created_at: :asc).all
    
    if Current.user.nil?
      @user_is_teacher = false
    elsif Current.user.teacher?
      @user_is_teacher = true
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
    @comments = Comment.where(lesson_id: @lesson.id, parent_id: nil)
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      overview_section = @lesson.sections.new(header: "Overview")
      vocab_section = @lesson.sections.new(header: "Vocabulary")

      overview_section.save!
      vocab_section.save!
      redirect_to edit_lesson_path(@lesson)
    else
      flash[:alert] = @lesson.errors.full_messages.to_sentence
      redirect_to new_lesson_path(@lesson)
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update(lesson_params)
      redirect_to edit_lesson_path(@lesson)
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to lessons_path, alert: "Lesson deleted"
  end

  private
  
  def lesson_params
    params.require(:lesson).permit( :title, :season, :status )
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_edit_nav.html.erb
<div id="edit-nav">
  <%= link_to "New Lesson", new_lesson_path() %> <br>
  <%= link_to "Edit Lesson Top", edit_lesson_path(@lesson) %> <br>
  <%= link_to "Add Section", new_lesson_section_path(@lesson) %> <br>
  <br>
  <span>Current Sections</span>
  <ul>
    <% @lesson.get_sections.sort_by(&:created_at).each do |section| %>
      <% if section.valid? %>
        <li><%= link_to section.header, edit_lesson_section_path(@lesson, section) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/lessons/_form.html.erb
<%= form_with model: lesson do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, {size: 35, class: "form-control", placeholder: "Episode Title"}  %>
  </div>
  <div class="mb-3">
    <%= form.label :season, class: "form-label" %>
    <%= form.select :season,
        [["1", 1],
        ["2", 2],
        ["3", 3],
        ["4", 4],
        ["5", 5],
        ["6", 6],
        ["7", 7],
        ["8", 8],
        ["9", 9],
        ["10", 10]]%>
  </div>
  <div class="mb-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, [["hidden", "hidden"], ["visible", "visible"]] %>
  </div>
  <div class="mb-3 crud-btn">
    <%= form.button class: "btn btn-secondary rounded-circle", title: "Save lesson" do %>
      <i class="fa-solid fa-floppy-disk"></i>
    <% end %>
    <% if lesson.persisted? %>
      <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, 
          lesson_path(lesson),
          method: :delete,
          data: { confirm: "All associated comments will be deleted. Delete lesson?" },
          class: "btn btn-secondary rounded-circle",
          title: "Delete" %>
    <% end %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="edit-main">
  <%= render "edit_nav" %>
  <div class="edit-forms">
    <h3>Edit Lesson Info:</h3>
    <%= render "form", lesson: @lesson %>
  </div>
  <div class="lesson-preview ">
    <%= render "shared/lesson_main" %>
  </div>
</div>

app/views/lessons/index.html.erb
<section id="main">
  <div class="container-fluid chalkboard">
    <div id="lesson-index">
      <h3>Lessons:</h3>
      <ul class="list-group mt-2">
        <% @lessons.each do |lesson| %>
          <% if @user_is_teacher %>
            <li class="list-group-item list-group-item-action lesson-list-row">
              <%= link_to lesson.title, lesson_path(lesson), class: "btn" %>
              <%= link_to '<i class="fa-solid fa-pencil"></i>'.html_safe , edit_lesson_path(lesson), class: "edit-lesson-link" %>
            </li>
          <% elsif lesson.visible? %>
            <li class="list-group-item list-group-item-action lesson-list-row">
              <%= link_to lesson.title, lesson_path(lesson), class: "btn" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <br>
      <span>
        <% if @user_is_teacher %>
          <%= link_to "New Lesson", new_lesson_path, class: "btn btn-light mb-3" %>
        <% end %>
      </span>
    </div>
  </div>
</section>

app/views/lessons/new.html.erb
<div class="center-content">
  <h1>New Lesson</h1>
  <%= render "form", lesson: @lesson %>
</div>

app/views/lessons/show.html.erb
<%= render "shared/lesson_main" %>
<div class="container lesson-footer">
  <h1>Comments</h1>
  <% if Current.user %>
    <%= render "comments/form", lesson: @lesson, comment: @lesson.comments.new, parent_id: nil %>
  <% else %>
    <p>
      コメントをするには
      <%= link_to "ログイン", sign_in_path %>
      または
      <%= link_to "新規登録", new_user_path %>
      して下さい。
    </p>
  <% end %>
  <% @comments.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
  <% end %>
</div>